apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    env: prod
    tier: front
    owner: adil
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    ports:
      - containerPort: 80
